<?php

class AdminReservarCitaControllerCore extends AdminController
{

    public function __construct()
    {
        $this->bootstrap = true;
        $this->table = 'reservar_cita';
        $this->className = 'ReservarCita';
        $this->lang = false;
        $this->context = Context::getContext();
//        $this->addRowAction('edit');
//        $this->addRowAction('delete');
//        $this->addRowAction('view');

        parent::__construct();
        
    }
    public function setMedia($isNewTheme = false)
    {
        parent::setMedia($isNewTheme); // TODO: Change the autogenerated stub

        $this->addCSS(__PS_BASE_URI__ . $this->admin_webpath . '/themes/default/js/fullcalendar/core/main.css');
        $this->addCSS(__PS_BASE_URI__ . $this->admin_webpath . '/themes/default/js/fullcalendar/daygrid/main.css');
        $this->addCSS(__PS_BASE_URI__ . $this->admin_webpath . '/themes/default/js/fullcalendar/timegrid/main.css');
        $this->addCSS(__PS_BASE_URI__ . $this->admin_webpath . '/themes/default/js/fullcalendar/list/main.css');
        $this->addJs(__PS_BASE_URI__ . $this->admin_webpath . '/themes/default/js/fullcalendar/core/main.js');
        $this->addJs(__PS_BASE_URI__ . $this->admin_webpath . '/themes/default/js/fullcalendar/core/locales/es.js');
        $this->addJs(__PS_BASE_URI__ . $this->admin_webpath . '/themes/default/js/fullcalendar/interaction/main.js');
        $this->addJs(__PS_BASE_URI__ . $this->admin_webpath . '/themes/default/js/fullcalendar/daygrid/main.js');
        $this->addJs(__PS_BASE_URI__ . $this->admin_webpath . '/themes/default/js/fullcalendar/timegrid/main.js');
        $this->addJs(__PS_BASE_URI__ . $this->admin_webpath . '/themes/default/js/fullcalendar/list/main.js');


        $this->addCSS(__PS_BASE_URI__ . $this->admin_webpath . '/themes/default/css/waitMe.min.css');
        $this->addJs(__PS_BASE_URI__ . $this->admin_webpath . '/themes/default/js/waitMe.min.js');

        $this->addJs(__PS_BASE_URI__ . $this->admin_webpath . '/themes/default/js/waitMe.min.js');
    }

    public function display()
    {
        $colaboradores = Employee::getEmployees(true);
        $this->context->smarty->assign(array(
            'colaboradores' => $colaboradores
        ));

        $this->display='reservar_cita';
        $this->tpl_folder='controllers'.DIRECTORY_SEPARATOR.Tools::toUnderscoreCase(substr($this->controller_name, 5)).'/';

        parent::display(); // TODO: Change the autogenerated stub
    }

    public function ajaxProcessGetCitasByColaborador()
    {
        $id_colaborador = Tools::getValue('id_colaborador');

        $citas = ReservarCita::getCitasByColadorador($id_colaborador);

        die(json_encode(array(
            "respuesta" => "ok",
            "citas" => $citas
        )));
    }
}